### ISSUE TITLE
Questions on 7-hop negatives

### ISSUE THREAD

**Issue by madnessfish** [Barabasi-Lab/AI-Bind#3]
Thank you for the interesting study to facilitate inductive prediction! I have learned a lot from your study. I have some questions about applying 7-hop negatives to my study.

1. What is the major function of 7-hop negatives? Whether it fixes the annotation imbalance? Or aim to create harder negatives for the model to learn (i.e., 7-hop but not 9 or 11-hop)?

2. I have tried to calculate the degree ratio (shown in the attached figures) in the resulting 7-hop negative sets (in VecNet_Unseen_Nodes/train_0.csv and VecNet_Unseen_Targets/train_0.csv). The degree ratio is evenly spread across node degree (except in degree ratio=1).

=> I wondered whether fixing the annotation imbalance means (I) do not have an extreme degree ratio across all drugs and targets or (ii) Keeping all the degree ratio the same (maybe all drug and target degree ratio=0.5)?  
<img width="1120" alt="Screenshot 2023-12-15 at 10 33 21 AM" src="https://github.com/Barabasi-Lab/AI-Bind/assets/29503972/20c30ca3-1c27-4984-8228-05acda4ac0f1">

3. Whether the original, experimental negatives (that may create annotation imbalance) are all discarded? i.e., All the negative instances in AI-bind are solely generated by 7-hop methods?

Again, thank you so much for this interesting work.

**Comment by ChatterjeeAyan** [comment]
Thanks for your interest in our work. 

1. 7 hop negatives help fix annotation imbalance since the negatives available in BindingDB are not sufficient to provide both positives and negatives for the majority of nodes. In Figure 5d (https://www.nature.com/articles/s41467-023-37572-z/figures/5), we show that the strength of binding changes inversely to the hop distance. Thus, we use 7 hop negatives (smallest hop distance for which Ki is above the binding threshold) for training, and 11-15 hop negatives (harder negatives) for validation and testing.

2. Fixing annotation imbalance means removing the nodes with only positive or negative samples. Thus, your understanding (i) do not have an extreme degree ratio across all drugs and targets - is correct, where extreme degree ratios are ==0 or ==1. 

3. Abolute negatives (experimental) are used in validation and testing along with 11-15 hop negatives.
